//const URL_ROOT = 'http://localhost:8000/api'
//const URL_ROOT_AUTH = 'http://localhost:8000'
const URL_ROOT = 'https://carmsanc.pythonanywhere.com/api';
const URL_ROOT_AUTH = 'https://carmsanc.pythonanywhere.com';

const URL_SERVICIOS = {
    url_backend: URL_ROOT_AUTH,
    camposantos : URL_ROOT + '/camposantos/',
    camposanto : URL_ROOT + '/camposanto/',
    difunto : URL_ROOT + '/difunto/',
    difunto_post : URL_ROOT + '/difunto_post/',
    difuntos : URL_ROOT + '/difuntos/',
    red_social_post: URL_ROOT + '/red_social_post/',
    red_social_put: URL_ROOT + '/red_social_put/',
    red_social: URL_ROOT + '/redes_sociales_camp/',
    sector: URL_ROOT + '/sector_camp/',
    sepultura: URL_ROOT + '/tipo_sepultura_camp/',
    responsable_post: URL_ROOT + '/responsable_difunto_post/',
    responsable_get: URL_ROOT + '/responsable_difunto_get/',
    geolocalizacion_post: URL_ROOT + '/geolocalizacion_post/',
    empresas: URL_ROOT + '/empresas/',
    empresa_get: URL_ROOT + '/empresa_get/',
    usuario: URL_ROOT_AUTH + '/users/',
    login: URL_ROOT + '/token/',
    refreshlogin: URL_ROOT_AUTH + 'api/token/refresh/ ',
    fblogin: URL_ROOT_AUTH + '/auth/convert-token/',
    obtener_usuarios: URL_ROOT + '/obtener_usuarios/',
    FBauth: URL_ROOT + '/get_token_facebook/',
    homenajes: URL_ROOT + '/homenajes/',
    homenaje_post: URL_ROOT + '/homenajes_post/',
    hmensaje_post: URL_ROOT + '/hmensaje_post/',
    himagen_post: URL_ROOT + '/himagen_post/',
    hvideo_post: URL_ROOT + '/hvideo_post/',
    haudio_post: URL_ROOT + '/haudio_post/',
    addRoses: URL_ROOT + '/difunto/update-partial/',
    registroRosa: URL_ROOT + '/historial_rosas_post/',
    logRosas: URL_ROOT + '/historial_rosas/',
    updateUser: URL_ROOT + '/usuario/',
    del_img: URL_ROOT + '/himagen_del/',
    del_video: URL_ROOT + '/hvideo_del/',
    del_mensaje: URL_ROOT + '/hmensaje_del/',
    del_audio: URL_ROOT + '/haudio_del/',
    del_youtube: URL_ROOT + '/hyoutube_del/',
    favoritos: URL_ROOT + '/favoritos/',
    favoritos_list: URL_ROOT + '/favoritos_list/',
    favoritos_del: URL_ROOT + '/favoritos_del/',
    recuperar_contrasena: URL_ROOT + '/enviar_email_password_admin/',
    recuperar_contrasenaCorreo: URL_ROOT + '/enviar_email_password/',
    paquetes: URL_ROOT + '/paquetes_list/',
    paquetes_recientes: URL_ROOT + '/paquetes_rec/',
    geolocalizacion_camp: URL_ROOT + '/geolocalizacion_camp/',
    contacto: URL_ROOT + '/contactoPost/',
    userInfo: URL_ROOT + '/usuario/',

};

export default URL_SERVICIOS;
